server:
  port: 80

spring:
  application:
    name: order-service

eureka:
  client:
    # 本身是客户端，需要注册
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
  instance:
    instance-id: order80
    # 访问路径可以显示ip地址
    prefer-ip-address: true
    # eureka客户端向服务端发送心跳的时间间隔，默认30喵
    lease-renewal-interval-in-seconds: 1
    # eureka服务端在收到最后一次心跳后的等待时间上限，默认为90秒，超时将剔除服务
    lease-expiration-duration-in-seconds: 3