server:
  port: 8002
spring:
  application:
    name: payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ssacgn.online:3306/cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: o@S$9i3r6V
  cloud:
    zookeeper:
      connect-string: localhost:2181



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: top.quezr.sc.entities
